author: Nathan West
name: Nathan West

pygments: true
permalink: pretty
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
